### PR TITLE
Simplify if err != nil block to just return err

### LINKED ISSUE #132: Generated code does not pass gosimple linter
The [`gosimple`](https://github.com/dominikh/go-simple) tool flags this issue with the generated code.

```go
// restore.go
err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
if err != nil {
	return err
}
return nil
```
This can be simplified to:
```go
return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
```

It is semantically identical.

We noticed the issue because we use `gosimple` as part of our CI pipeline.

### PR DESCRIPTION
**Pull request by y0ssar1an**
Fixes #132.

go-bindata inserts code that does not pass the [`gosimple` linter](https://github.com/dominikh/go-simple). We want to use this linter as part of our CI pipeline at [Apcera](https://www.apcera.com), but the code inserted by `go-bindata` is blocking us :(
### Steps to reproduce

``` sh
go get go get honnef.co/go/simple/cmd/gosimple
cd $GOPATH/src/github.com/jteeuwen/go-bindata
gosimple ./...
```
### The fix

The issue is trivial.

``` go
if err != nil {
    return err
}
return nil

// The above is semantically identical to this
return err
```

I submitted a PR for this previously, but I closed it because I thought it had been merged. I was wrong. I believe it was merged into a separate repo. I'm not sure how your dev process works. Sorry about that.

### CODE REVIEW

**Comment by y0ssar1an** [comment]
Closing because this repo is abandoned.

**Comment by martinlindhe** [comment]
@y0ssar1an is there a repo that supersedes this one?

**Comment by y0ssar1an** [comment]
@martinlindhe Yes! As discussed in #134, the community is switching to https://github.com/tmthrgd/go-bindata. It's already got hundreds of commits. I'm gonna submit all my future PRs to that repo.

**Comment by martinlindhe** [comment]
@y0ssar1an thanks :) I wasn't aware

**Pull request closed without merging**
